run:
  timeout: 10m
  modules-download-mode: vendor
  skip-dirs:
    - (^|/)vendor($|/)
    - pkg/utils/lifted
    - pkg/scheduler/lifted
linters:
  disable-all: true
  enable:
    # linters maintained by golang.org
    - gofmt
    - govet
    - goimports
    # linters default enabled by golangci-lint .
    - errcheck
    - gosimple
    - typecheck
    - staticcheck
    - ineffassign
    - unused
    # other linters supported by golangci-lint.
    - gci
    - misspell
    - bodyclose
    - gocyclo
    - gosec
    - dupl
    - revive
    - whitespace
linters-settings:
  goimports:
    local-prefixes: github.com/kosmos.io/kosmos
  misspell:
    ignore-words:
      - creater
  gci:
    sections:
      - Standard
      - Default
      - Prefix(github.com/kosmos.io/kosmos)
  gocyclo:
    # minimal cyclomatic complexity to report
    min-complexity: 40 # The recommended value is 15
output:
  sort-results: true




