apiVersion: kubescheduler.config.k8s.io/v1beta2
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
clientConnection:
  kubeconfig: /Users/duanmeng/Code/github/kosmos/kubeconfig
profiles:
  - schedulerName: kosmos-scheduler
    plugins:
      preFilter:
        disabled:
          - name: "VolumeBinding"
      filter:
        disabled:
          - name: "VolumeBinding"
        enabled:
          - name: "KNodeTaintToleration"
