//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package config

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeafNodeDistributionArgs) DeepCopyInto(out *LeafNodeDistributionArgs) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeafNodeDistributionArgs.
func (in *LeafNodeDistributionArgs) DeepCopy() *LeafNodeDistributionArgs {
	if in == nil {
		return nil
	}
	out := new(LeafNodeDistributionArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LeafNodeDistributionArgs) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LeafNodeVolumeBindingArgs) DeepCopyInto(out *LeafNodeVolumeBindingArgs) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LeafNodeVolumeBindingArgs.
func (in *LeafNodeVolumeBindingArgs) DeepCopy() *LeafNodeVolumeBindingArgs {
	if in == nil {
		return nil
	}
	out := new(LeafNodeVolumeBindingArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LeafNodeVolumeBindingArgs) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
