apiVersion: v1
kind: Service
metadata:
  name: clusterlink-proxy-service
  namespace: kosmos-system
spec:
  selector:
    app: clusterlink-proxy
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 32443
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusterlink-proxy
  namespace: kosmos-system
  labels:
    app: clusterlink-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clusterlink-proxy
  template:
    metadata:
      labels:
        app: clusterlink-proxy
    spec:
      containers:
        - name: clusterlink-proxy
          image: ghcr.io/kosmos-io/clusterlink-proxy:__VERSION__
          imagePullPolicy: IfNotPresent
          command:
            - clusterlink-proxy
            - --kubeconfig=/etc/clusterlink/kubeconfig
            - --authentication-kubeconfig=/etc/clusterlink/kubeconfig
            - --authorization-kubeconfig=/etc/clusterlink/kubeconfig
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 500Mi
          readinessProbe:
            exec:
              command:
                - cat
                - /proc/1/cmdline
            failureThreshold: 30
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 30
            exec:
              command:
                - cat
                - /proc/1/cmdline
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          volumeMounts:
            - mountPath: /etc/clusterlink
              name: proxy-config
              readOnly: true
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - clusterlink-proxy
            namespaces:
              - {{ .Namespace }}
            topologyKey: kubernetes.io/hostname
      volumes:
        - name: proxy-config
          configMap:
            defaultMode: 420
            name: clusterlink-agent-proxy
