apiVersion: v1
kind: ServiceAccount
metadata:
  name: clustertree-cluster-manager
  namespace: kosmos-system
---
apiVersion: v1
data:
  Kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        insecure-skip-tls-verify: true
        server: https://[2409:8720:4a00::1:644a:5f13]:6443
      name: cluster.local
    contexts:
    - context:
        cluster: cluster.local
        user: kubernetes-admin
      name: kubernetes-admin@cluster.local
    current-context: kubernetes-admin@cluster.local
    kind: Config
    preferences: {}
    users:
    - name: kubernetes-admin
      user:
        client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lJS1ltanowaHhvU0F3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TXpBMk1UVXhNRFF4TWpOYUZ3MHpNekEyTVRJeE1EUXhNalZhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTBJS0cvQnVXRXJSL0w3QmEKWExmYUZpbVovRTY5VlpTMjNyd2JORWk4U2pSUEs4SE41VU53UXlBNEIwVG1WTkxLYU5vWWVOd2pmWDRWYlVJbwpMY29uU2dudGttamRuc1g1SURDRWY2UjFGT3pzVXFMbFR3aXJ4cjlSNGw0QjdrQi95T1ordFlhQzNUaWFvNGc4Ck9LdkVaU0tWblRvVUptcU5CSHRCZkoxVFU0VE12cmFoaTN2b2YwWWpKR0o4ck1PYmVtWERuOTU1S1JucWlJTGYKZ1ZZY3pOL0pDRldvbEoybkNNeGhMcnNWMlZQakNnN2s3UWZMNDJEUlBZZS9icXN1S01Mc0VoTzVPOTh5Y1JnaApZNkhnV2thazc3U3RmOHNoUnFyRE5vTjhDbnp5S0wrbmdMTEJYUW9tUDkxZHNMOVlEU2FrSkI2SlQ3Ly9xa2RDCnNtVXROUUlEQVFBQm8xWXdWREFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXZ0JRclhiUHhLdDdCSWVEQk9MZG43WkdRcVlVUwpVakFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBZUNROXJ6WGdmd2JaaEUzeXA3bmNxQjlzcFdXdXpjQUFkRDVFCmtXSU1jZ3Rwc1RxTUR5YlVhOUp6WTdRNExtSEI4M3psYTRJWmJNVnFDVTdXTlZFLzZQYU5rNGUzU1Q1NERqbEYKUmFRTjBWMHdQTitIRldOZTkwRlFiSCtYMGp2b3ZEU3JIL2t4WGdLWnFNbTlHMWZRRW9jUG1wWWdpdWUvTi81VwpSdkI4Y1B2RlpMTjVhNG9Wa3NjUEp5Z2dRbzFDbU5PNmFNQkFaYlVmZjR4QjVuL0t2eklDT0pCTTJiK3R3VVNkCmpzcjU2ZkxCYk5MbUNaTWpURDk3SnRrMmgvMmU0dHFUY3dON0RsK2ZpRTdSYm9VMGJmekxBVjFUQXhLbHI2NGQKdFBPbXBDY0xRV0lVWnFIMzNMM3I5VHRBVUtsZHB2SjlvMlo3eEkzNW5XSTVZdWxGOFE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBMElLRy9CdVdFclIvTDdCYVhMZmFGaW1aL0U2OVZaUzIzcndiTkVpOFNqUlBLOEhOCjVVTndReUE0QjBUbVZOTEthTm9ZZU53amZYNFZiVUlvTGNvblNnbnRrbWpkbnNYNUlEQ0VmNlIxRk96c1VxTGwKVHdpcnhyOVI0bDRCN2tCL3lPWit0WWFDM1RpYW80ZzhPS3ZFWlNLVm5Ub1VKbXFOQkh0QmZKMVRVNFRNdnJhaAppM3ZvZjBZakpHSjhyTU9iZW1YRG45NTVLUm5xaUlMZmdWWWN6Ti9KQ0ZXb2xKMm5DTXhoTHJzVjJWUGpDZzdrCjdRZkw0MkRSUFllL2Jxc3VLTUxzRWhPNU85OHljUmdoWTZIZ1drYWs3N1N0ZjhzaFJxckROb044Q256eUtMK24KZ0xMQlhRb21QOTFkc0w5WURTYWtKQjZKVDcvL3FrZENzbVV0TlFJREFRQUJBb0lCQUd0UVlxenFmY2pPd1E4SQpVdG1aZmxNZHdqVUxTWUw4Y1VvZHdscWNmTndzSS9zL1dmci9SSTRuek81ZzFiTWVjaktZM1RPSENYVVRLVy84Ck5yV3FiNkk1amQ1bXZubHpKdzhjS1hXUWJQb0NIbmRCZzRlenpNVVR2czhrMXhXS2VMb3JkMWR5RFhSU0o3UzIKNzFlemYvY1ZYNjkyTHR5K3hpbGlUb2dXYU1aNGlsb2hMWEFEanlIY0JMUFR0RjdqbHI5ajVFZXlSOTJYcENMbAoxaTY1TGxNeE11aE40eUVNZS9uUWY2Wi81NXJQNkVqNTNud2VkTEppTFRhNjJDbGJSWlVPV3BtdEtncGVsYVQ3Cis3TlppQ0VadWNaSm0zNnp1Ukw1eEpROEYyVUoyUkduVjlyeFdKcm91bm5uT3E3TzRpYnlaSzcvT0k4V0UvTW4KUVNHRVNrRUNnWUVBMVRxcEgxcE1YK09LMjdPbWhDYkJXVFhrZ25WanRDSEZtRk5MQnpPMUIrcWZIT2EvemJ5bgpOZHlYVE5MOHdhaHBTWlY3WGdaV0R2VDU1M3p4MjlsbHZXU3JlZlpZRG1XSDhYaXRRSXliUlA0ei91K3NoN0hiCjQrclAvMjNPbW9aM3FwaHFvMDRmTTRyY3h2NjZSYThzS0N6VmpXVUtwang2K0JtSW11bjVobmtDZ1lFQStsV0kKRmRGT0pFYnlNWmt6Q1Vib2xBQkUwQlV4bjZTUG5TRVBaaDZyU2hISVo5QUpLVi9oc3dTOHhaMk1wV0ZMOTN3ZQpoMHZBV1h3Z0IweTBybUM5WVhaekdmSkR6RXZQSjg1blliK0lzcTkvN3VnUmZCRUF2a0cxbENheExoSmt4YW1lCko0Q3FSQWc4YTJTazA4NFRISVlhQlZzQU44bjZsUU0zNS9DeUhaMENnWUFmcHBWMEVmTkVTSUpVR2xhZFJ5TnMKR3BQUXlad0RJUUF6bkNtRzZDWDNCdHlYYmFrSzRQWHhDTTFzbWVUcTJoVEcxMmw0aTNnNndDSllPak9zYnBpcgpoRVh2MUtFOWdkU3NBejIwVnlxMUV3YWswTzdMTlp0dU9XeW1mYVl0U2NoNWlpWktGMDZLV0JKdGQySXU5ZEdZCkpRK043WEduTzFNRmdNVEdPZlRRQVFLQmdRQ0NKV1dTc2phRjlieUV2TGtqNFpHWklHcW1JOTZndU5WUlE1YlYKNkt2MDNqbnFmdVhFZE96S1BYUkc2Um51QVIrVmt4bnNEUjM3WitUZTVxb28zbktXOFJYMkwxWEFLTW1TVUdTLwpGT3prdVFreUU4VERVN09uTmxKSXE3VUIxdDQ5UlduTDc4Q1ZqaEtiWXIrdXZqeUJYOWEzWWhCQzhPY3VBWFpYClIzUFNvUUtCZ0ZyalIxNmdORWVmdDRqZEdCd29FNXJFR1RtMm1GQlVhSitrcmtNKzFWbEhoazJPa1ZySSt5a1IKbURFMnlPc2lkQXhYazMzVThKT3Rva2ZVc0gzM1pQWXZNa29pMXdETUhBNVFOTWUvNkV4U0dGczNuRytzYkt4egoyNVM3bnpPUVVPSEFnOUptK0VvWlVzNnE4ck4xMy84eEpDRnptVFNnakhVZWUvTXpGRWxlCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
kind: ConfigMap
metadata:
  name: host-kubeconfig
  namespace: kosmos-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clustertree-cluster-manager
  namespace: kosmos-system
  labels:
    app: clustertree-cluster-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clustertree-cluster-manager
  template:
    metadata:
      labels:
        app: clustertree-cluster-manager
    spec:
      containers:
        - name: clustertree-cluster-manager
          image: ghcr.io/kosmos-io/clustertree-cluster-manager:__VERSION__
          imagePullPolicy: Always
          command:
            - clustertree-cluster-manager
            - --kube-api-qps=500
            - --kube-api-burst=1000
            - --kubeconfig=/etc/kube/config
            - --leader-elect=false
          volumeMounts:
            - mountPath: /etc/kube
              name: config-volume
              readOnly: true
      serviceAccountName: clustertree-cluster-manager
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: kubeconfig
                path: config
            name: host-kubeconfig
          name: config-volume