apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: clusterlink-agent
  namespace: kosmos-system
spec:
  selector:
    matchLabels:
      app: clusterlink-agent
  template:
    metadata:
      labels:
        app: clusterlink-agent
    spec:
      tolerations:
        # these tolerations are to have the daemonset runnable on control plane nodes
        # remove them if your control plane nodes should not run pods
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: clusterlink-agent
          image: ghcr.io/kosmos-io/clusterlink-agent:__VERSION__
          imagePullPolicy: IfNotPresent
          command:
            - clusterlink-agent
            - -kubeconfig=/etc/clusterlink/kubeconfig
            - --v=4
          env:
            - name: CLUSTER_NAME
              value: ""
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            limits:
              memory: 200Mi
              cpu: 250m
            requests:
              cpu: 250m
              memory: 200Mi
          volumeMounts:
          - mountPath: /etc/clusterlink/kubeconfig
            name: proxy-config
            readOnly: true
          - mountPath: /run/xtables.lock
            name: iptableslock
            readOnly: false
          - mountPath: /lib/modules
            name: lib-modules
            readOnly: true
      terminationGracePeriodSeconds: 30
      securityContext:
        privileged: true
      hostNetwork: true
      volumes:
      - name: proxy-config
        configMap:
          defaultMode: 420
          name: proxy-config
      - hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
        name: iptableslock
      - name: lib-modules
        hostPath:
          path: /lib/modules

      
