apiVersion: v1
kind: ServiceAccount
metadata:
  name:  kosmos-operator
  namespace: kosmos-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kosmos-operator
  namespace: kosmos-system
  labels:
    app: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      containers:
      - name: operator
        image: ghcr.io/kosmos-io/kosmos-operator:__VERSION__
        imagePullPolicy: IfNotPresent
        command:
          - kosmos-operator
          - --controlpanelconfig=/etc/kosmos-operator/kubeconfig
        env:
          - name: VERSION
            value: __VERSION__
          - name: USE_PROXY
            value: "false"
        resources:
          limits:
            cpu: 250m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
          - mountPath: /etc/kosmos-operator
            name: proxy-config
            readOnly: true
      serviceAccountName: kosmos-operator
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - operator
              namespaces:
                - kosmos-system
              topologyKey: kubernetes.io/hostname
      volumes:
        - name: proxy-config
          secret:
            defaultMode: 420
            secretName: controlpanel-config
