apiVersion: v1
kind: ServiceAccount
metadata:
  name:  clusterlink-operator
  namespace: kosmos-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusterlink-operator
  namespace: kosmos-system
  labels:
    app: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      serviceAccountName: clusterlink-operator
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - operator
              namespaces:
                - kosmos-system
              topologyKey: kubernetes.io/hostname
      containers:
      - name: operator
        image: ghcr.io/kosmos-io/clusterlink-operator:__VERSION__
        imagePullPolicy: IfNotPresent
        command:
          - clusterlink-operator
          - --controlpanelconfig=/etc/clusterlink-operator/kubeconfig
        resources:
          limits:
            memory: 200Mi
            cpu: 250m
          requests:
            cpu: 100m
            memory: 200Mi
        env:
        - name: VERSION
          value: __VERSION__
        - name: USE_PROXY
          value: "false"
        volumeMounts:
          - mountPath: /etc/clusterlink-operator
            name: proxy-config
            readOnly: true
      volumes:
        - name: proxy-config
          secret:
            secretName: controlpanel-config
