// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	config "github.com/kosmos.io/kosmos/pkg/apis/config"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*KnodeVolumeBindingArgs)(nil), (*config.KnodeVolumeBindingArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_KnodeVolumeBindingArgs_To_config_KnodeVolumeBindingArgs(a.(*KnodeVolumeBindingArgs), b.(*config.KnodeVolumeBindingArgs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.KnodeVolumeBindingArgs)(nil), (*KnodeVolumeBindingArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_KnodeVolumeBindingArgs_To_v1beta1_KnodeVolumeBindingArgs(a.(*config.KnodeVolumeBindingArgs), b.(*KnodeVolumeBindingArgs), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_KnodeVolumeBindingArgs_To_config_KnodeVolumeBindingArgs(in *KnodeVolumeBindingArgs, out *config.KnodeVolumeBindingArgs, s conversion.Scope) error {
	out.BindTimeoutSeconds = in.BindTimeoutSeconds
	return nil
}

// Convert_v1beta1_KnodeVolumeBindingArgs_To_config_KnodeVolumeBindingArgs is an autogenerated conversion function.
func Convert_v1beta1_KnodeVolumeBindingArgs_To_config_KnodeVolumeBindingArgs(in *KnodeVolumeBindingArgs, out *config.KnodeVolumeBindingArgs, s conversion.Scope) error {
	return autoConvert_v1beta1_KnodeVolumeBindingArgs_To_config_KnodeVolumeBindingArgs(in, out, s)
}

func autoConvert_config_KnodeVolumeBindingArgs_To_v1beta1_KnodeVolumeBindingArgs(in *config.KnodeVolumeBindingArgs, out *KnodeVolumeBindingArgs, s conversion.Scope) error {
	out.BindTimeoutSeconds = in.BindTimeoutSeconds
	return nil
}

// Convert_config_KnodeVolumeBindingArgs_To_v1beta1_KnodeVolumeBindingArgs is an autogenerated conversion function.
func Convert_config_KnodeVolumeBindingArgs_To_v1beta1_KnodeVolumeBindingArgs(in *config.KnodeVolumeBindingArgs, out *KnodeVolumeBindingArgs, s conversion.Scope) error {
	return autoConvert_config_KnodeVolumeBindingArgs_To_v1beta1_KnodeVolumeBindingArgs(in, out, s)
}
