apiVersion: kosmos.io/v1alpha1
kind: VirtualCluster
metadata:
  name: test
  namespace: test-1
spec:
  kubeconfig: xxxx
  promoteResources:
    nodes:
      - node1
      - node2
    resources:
      limits:
        cpu: 1
        memory: "1Gi"
      requests:
        cpu: 1
        memory: "500Mi"