apiVersion: kosmos.io/v1alpha1
kind: VirtualCluster
metadata:
  namespace: test
  name: test
spec:
  externalIP: 127.0.0.8
  promotePolicies:
  - labelSelector:
      matchLabels:
        machine.ecloud.cmss.com/specsname: g4t.8xlarge.8
    nodeCount: 1
  promoteResources:
    nodeInfos:
    - nodeName: nodeName1
