apiVersion: kosmos.io/v1alpha1
kind: VirtualCluster
metadata:
  namespace: test
  name: test
spec:
  externalIP: 127.0.0.10
  promotePolicies:
    - labelSelector:
        matchLabels:
          kubernetes.io/hostname: label1
      nodeCount: 1
  promoteResources:
    nodeInfos:
      - nodeName: nodeName1
