//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kosmos Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	config "github.com/kosmos.io/kosmos/pkg/apis/config"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*LeafNodeVolumeBindingArgs)(nil), (*config.LeafNodeVolumeBindingArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_LeafNodeVolumeBindingArgs_To_config_LeafNodeVolumeBindingArgs(a.(*LeafNodeVolumeBindingArgs), b.(*config.LeafNodeVolumeBindingArgs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.LeafNodeVolumeBindingArgs)(nil), (*LeafNodeVolumeBindingArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_LeafNodeVolumeBindingArgs_To_v1_LeafNodeVolumeBindingArgs(a.(*config.LeafNodeVolumeBindingArgs), b.(*LeafNodeVolumeBindingArgs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*UtilizationShapePoint)(nil), (*config.UtilizationShapePoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_UtilizationShapePoint_To_config_UtilizationShapePoint(a.(*UtilizationShapePoint), b.(*config.UtilizationShapePoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.UtilizationShapePoint)(nil), (*UtilizationShapePoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_UtilizationShapePoint_To_v1_UtilizationShapePoint(a.(*config.UtilizationShapePoint), b.(*UtilizationShapePoint), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_LeafNodeVolumeBindingArgs_To_config_LeafNodeVolumeBindingArgs(in *LeafNodeVolumeBindingArgs, out *config.LeafNodeVolumeBindingArgs, s conversion.Scope) error {
	if err := metav1.Convert_Pointer_int64_To_int64(&in.BindTimeoutSeconds, &out.BindTimeoutSeconds, s); err != nil {
		return err
	}
	out.Shape = *(*[]config.UtilizationShapePoint)(unsafe.Pointer(&in.Shape))
	return nil
}

// Convert_v1_LeafNodeVolumeBindingArgs_To_config_LeafNodeVolumeBindingArgs is an autogenerated conversion function.
func Convert_v1_LeafNodeVolumeBindingArgs_To_config_LeafNodeVolumeBindingArgs(in *LeafNodeVolumeBindingArgs, out *config.LeafNodeVolumeBindingArgs, s conversion.Scope) error {
	return autoConvert_v1_LeafNodeVolumeBindingArgs_To_config_LeafNodeVolumeBindingArgs(in, out, s)
}

func autoConvert_config_LeafNodeVolumeBindingArgs_To_v1_LeafNodeVolumeBindingArgs(in *config.LeafNodeVolumeBindingArgs, out *LeafNodeVolumeBindingArgs, s conversion.Scope) error {
	if err := metav1.Convert_int64_To_Pointer_int64(&in.BindTimeoutSeconds, &out.BindTimeoutSeconds, s); err != nil {
		return err
	}
	out.Shape = *(*[]UtilizationShapePoint)(unsafe.Pointer(&in.Shape))
	return nil
}

// Convert_config_LeafNodeVolumeBindingArgs_To_v1_LeafNodeVolumeBindingArgs is an autogenerated conversion function.
func Convert_config_LeafNodeVolumeBindingArgs_To_v1_LeafNodeVolumeBindingArgs(in *config.LeafNodeVolumeBindingArgs, out *LeafNodeVolumeBindingArgs, s conversion.Scope) error {
	return autoConvert_config_LeafNodeVolumeBindingArgs_To_v1_LeafNodeVolumeBindingArgs(in, out, s)
}

func autoConvert_v1_UtilizationShapePoint_To_config_UtilizationShapePoint(in *UtilizationShapePoint, out *config.UtilizationShapePoint, s conversion.Scope) error {
	out.Utilization = in.Utilization
	out.Score = in.Score
	return nil
}

// Convert_v1_UtilizationShapePoint_To_config_UtilizationShapePoint is an autogenerated conversion function.
func Convert_v1_UtilizationShapePoint_To_config_UtilizationShapePoint(in *UtilizationShapePoint, out *config.UtilizationShapePoint, s conversion.Scope) error {
	return autoConvert_v1_UtilizationShapePoint_To_config_UtilizationShapePoint(in, out, s)
}

func autoConvert_config_UtilizationShapePoint_To_v1_UtilizationShapePoint(in *config.UtilizationShapePoint, out *UtilizationShapePoint, s conversion.Scope) error {
	out.Utilization = in.Utilization
	out.Score = in.Score
	return nil
}

// Convert_config_UtilizationShapePoint_To_v1_UtilizationShapePoint is an autogenerated conversion function.
func Convert_config_UtilizationShapePoint_To_v1_UtilizationShapePoint(in *config.UtilizationShapePoint, out *UtilizationShapePoint, s conversion.Scope) error {
	return autoConvert_config_UtilizationShapePoint_To_v1_UtilizationShapePoint(in, out, s)
}
