//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	config "github.com/kosmos.io/kosmos/pkg/apis/config"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*KnodeVolumeBindingArgs)(nil), (*config.KnodeVolumeBindingArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_KnodeVolumeBindingArgs_To_config_KnodeVolumeBindingArgs(a.(*KnodeVolumeBindingArgs), b.(*config.KnodeVolumeBindingArgs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.KnodeVolumeBindingArgs)(nil), (*KnodeVolumeBindingArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_KnodeVolumeBindingArgs_To_v1_KnodeVolumeBindingArgs(a.(*config.KnodeVolumeBindingArgs), b.(*KnodeVolumeBindingArgs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*UtilizationShapePoint)(nil), (*config.UtilizationShapePoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_UtilizationShapePoint_To_config_UtilizationShapePoint(a.(*UtilizationShapePoint), b.(*config.UtilizationShapePoint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.UtilizationShapePoint)(nil), (*UtilizationShapePoint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_UtilizationShapePoint_To_v1_UtilizationShapePoint(a.(*config.UtilizationShapePoint), b.(*UtilizationShapePoint), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_KnodeVolumeBindingArgs_To_config_KnodeVolumeBindingArgs(in *KnodeVolumeBindingArgs, out *config.KnodeVolumeBindingArgs, s conversion.Scope) error {
	if err := metav1.Convert_Pointer_int64_To_int64(&in.BindTimeoutSeconds, &out.BindTimeoutSeconds, s); err != nil {
		return err
	}
	out.Shape = *(*[]config.UtilizationShapePoint)(unsafe.Pointer(&in.Shape))
	return nil
}

// Convert_v1_KnodeVolumeBindingArgs_To_config_KnodeVolumeBindingArgs is an autogenerated conversion function.
func Convert_v1_KnodeVolumeBindingArgs_To_config_KnodeVolumeBindingArgs(in *KnodeVolumeBindingArgs, out *config.KnodeVolumeBindingArgs, s conversion.Scope) error {
	return autoConvert_v1_KnodeVolumeBindingArgs_To_config_KnodeVolumeBindingArgs(in, out, s)
}

func autoConvert_config_KnodeVolumeBindingArgs_To_v1_KnodeVolumeBindingArgs(in *config.KnodeVolumeBindingArgs, out *KnodeVolumeBindingArgs, s conversion.Scope) error {
	if err := metav1.Convert_int64_To_Pointer_int64(&in.BindTimeoutSeconds, &out.BindTimeoutSeconds, s); err != nil {
		return err
	}
	out.Shape = *(*[]UtilizationShapePoint)(unsafe.Pointer(&in.Shape))
	return nil
}

// Convert_config_KnodeVolumeBindingArgs_To_v1_KnodeVolumeBindingArgs is an autogenerated conversion function.
func Convert_config_KnodeVolumeBindingArgs_To_v1_KnodeVolumeBindingArgs(in *config.KnodeVolumeBindingArgs, out *KnodeVolumeBindingArgs, s conversion.Scope) error {
	return autoConvert_config_KnodeVolumeBindingArgs_To_v1_KnodeVolumeBindingArgs(in, out, s)
}

func autoConvert_v1_UtilizationShapePoint_To_config_UtilizationShapePoint(in *UtilizationShapePoint, out *config.UtilizationShapePoint, s conversion.Scope) error {
	out.Utilization = in.Utilization
	out.Score = in.Score
	return nil
}

// Convert_v1_UtilizationShapePoint_To_config_UtilizationShapePoint is an autogenerated conversion function.
func Convert_v1_UtilizationShapePoint_To_config_UtilizationShapePoint(in *UtilizationShapePoint, out *config.UtilizationShapePoint, s conversion.Scope) error {
	return autoConvert_v1_UtilizationShapePoint_To_config_UtilizationShapePoint(in, out, s)
}

func autoConvert_config_UtilizationShapePoint_To_v1_UtilizationShapePoint(in *config.UtilizationShapePoint, out *UtilizationShapePoint, s conversion.Scope) error {
	out.Utilization = in.Utilization
	out.Score = in.Score
	return nil
}

// Convert_config_UtilizationShapePoint_To_v1_UtilizationShapePoint is an autogenerated conversion function.
func Convert_config_UtilizationShapePoint_To_v1_UtilizationShapePoint(in *config.UtilizationShapePoint, out *UtilizationShapePoint, s conversion.Scope) error {
	return autoConvert_config_UtilizationShapePoint_To_v1_UtilizationShapePoint(in, out, s)
}
